@startuml
skinparam classAttributeIconSize 0
hide circle

abstract class "Module\n{abstract}" as Module {
  # name: String
  # description: String
  {abstract} +run(data: Data): Data
}

Module <|-right- Base64Decoder
Module <|-right- Base64Encoder
Module <|-left- HexDecoder
Module <|-left- HexEncoder
Module <|-down- BinaryEncoder
Module <|-down- BinaryDecoder
Module <|-up- RotEncoder

class Base64Encoder {
  +run(data: Data): Data
}

class Base64Decoder {
  +run(data: Data): Data
}

class HexEncoder {
  +run(data: Data): Data
}

class HexDecoder {
  +run(data: Data): Data
}

class BinaryEncoder {
  +run(data: Data): Data
}

class BinaryDecoder {
  +run(data: Data): Data
}

class RotEncoder {
  - rotateOffset: int
  +run(data: Data): Data
}


@enduml