@startuml
skinparam classAttributeIconSize 0
hide circle

!include colors.puml

Decodex -> "1" Ui

class Decodex DECODEX_COLOR {
  - initDecodex(): void
  + run(): void
  + {static} main(): void
  - loadSavedRecipes(): void
}


class Ui UI_COLOR {
  - in: Scanner
  + readInput(): String
  + printSuccess(input: String): void
  + printError(exception: Exception): void
}

note right
  Only the commonly used
  methods are listed.
end note

@enduml