@startuml
!include ../../Style.puml

box LOGIC_COLOR
Participant ":ExitCommand" as ExitCommand
end box
box UI_COLOR
Participant ":Ui" as Ui
endbox

-> ExitCommand: run()
activate ExitCommand
ExitCommand -> Ui: printGoodbye()
activate Ui
ExitCommand <-- Ui
deactivate Ui
<-- ExitCommand

deactivate ExitCommand


@enduml