@startuml
!include ../../Style.puml

box LOGIC_COLOR
Participant ":InputCommand" as InputCommand
end box
box DATA_COLOR
Participant ":Data" as Data
Participant ":DataManager" as DataManager
end box
box UI_COLOR
Participant ":Ui" as Ui
end box

-> InputCommand: run()
activate InputCommand

alt dataString is not empty
  create Data
  InputCommand -> Data : new Data(data: String)
  activate Data
  InputCommand <-- Data: userData:Data
  deactivate Data
  InputCommand -> DataManager: setOriginalData(originalData: Data)
  activate DataManager
  InputCommand <-- DataManager
  deactivate DataManager
  InputCommand -> Ui: printInput(input: String)
  activate Ui
  InputCommand <-- Ui
  deactivate Ui
  <-- InputCommand
else dataString is empty
  <-- InputCommand: CommandException
  deactivate InputCommand
end

@enduml