@startuml
!include ../../Style.puml

box LOGIC_COLOR
Participant ":RecipePopCommand" as RecipePopCommand
end box
box RECIPE_COLOR
Participant ":RecipeManager" as RecipeManager
end box
box STORAGE_COLOR
Participant ":Storage" as Storage
end box
box UI_COLOR
Participant ":Ui" as Ui
end box

-> RecipePopCommand: run()
activate RecipePopCommand

RecipePopCommand -> RecipeManager: popModuleFromEditedRecipe()
activate RecipeManager
RecipePopCommand <-- RecipeManager: :Module
deactivate RecipeManager

RecipePopCommand -> Storage: saveRecipeToFile(:Recipe)
activate Storage
RecipePopCommand <-- Storage
deactivate Storage

RecipePopCommand -> RecipeManager: getEditingRecipe()
activate RecipeManager
RecipePopCommand <-- RecipeManager: :Recipe
deactivate RecipeManager

RecipePopCommand -> Ui: printModuleRemovedFromRecipe(:String, :String)
activate Ui
RecipePopCommand <-- Ui
deactivate Ui

<-- RecipePopCommand
deactivate RecipePopCommand

@enduml