@startuml
!include ../../Style.puml

box LOGIC_COLOR
Participant ":SelectCommand" as SelectCommand
end box
box MODULE_COLOR
Participant ":ModuleManager" as ModuleManager
Participant ":Module" as Module
end box
box DATA_COLOR
Participant ":DataManager" as DataManager
end box
box UI_COLOR
Participant ":Ui" as Ui
end box

-> SelectCommand: run()
activate SelectCommand

alt moduleName is not blank
  SelectCommand -> ModuleManager: selectModule(moduleName: String, parameters: String[])
  activate ModuleManager
  SelectCommand <-- ModuleManager: module: Module
  deactivate ModuleManager

  SelectCommand -> DataManager: getCurrentData()
  activate DataManager
  SelectCommand <-- DataManager: :Data
  deactivate DataManager

  SelectCommand -> Module: run(data: Data)
  activate Module
  SelectCommand <-- Module: newData: Data
  deactivate Module

  SelectCommand -> DataManager: setCurrentData(currentData: Data)
  activate DataManager
  SelectCommand <-- DataManager
  deactivate DataManager

  SelectCommand -> Ui: printOutput(newData)
  activate Ui
  SelectCommand <-- Ui
  deactivate Ui

  <-- SelectCommand
else moduleName is blank
  <-- SelectCommand: CommandException
  deactivate SelectCommand
end

@enduml